/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/SRAM_MEM.v:1.1-56.10" *)
module SRAM10x2048(clk0, csb0, addr0, din0, clk1, csb1, addr1, dout1);
  (* src = "src/SRAM_MEM.v:8.9-8.13" *)
  input clk0;
  wire clk0;
  (* src = "src/SRAM_MEM.v:9.9-9.13" *)
  input csb0;
  wire csb0;
  (* src = "src/SRAM_MEM.v:10.27-10.32" *)
  input [10:0] addr0;
  wire [10:0] addr0;
  (* src = "src/SRAM_MEM.v:11.27-11.31" *)
  input [9:0] din0;
  wire [9:0] din0;
  (* src = "src/SRAM_MEM.v:12.9-12.13" *)
  input clk1;
  wire clk1;
  (* src = "src/SRAM_MEM.v:13.9-13.13" *)
  input csb1;
  wire csb1;
  (* src = "src/SRAM_MEM.v:14.27-14.32" *)
  input [10:0] addr1;
  wire [10:0] addr1;
  (* src = "src/SRAM_MEM.v:15.26-15.31" *)
  output [9:0] dout1;
  wire [9:0] dout1;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "src/SRAM_MEM.v:18.8-18.14" *)
  wire csb0_0;
  (* src = "src/SRAM_MEM.v:19.8-19.14" *)
  wire csb0_1;
  (* src = "src/SRAM_MEM.v:21.8-21.14" *)
  wire csb1_0;
  (* src = "src/SRAM_MEM.v:22.8-22.14" *)
  wire csb1_1;
  (* src = "src/SRAM_MEM.v:24.25-24.32" *)
  wire [9:0] dout1_0;
  (* src = "src/SRAM_MEM.v:25.25-25.32" *)
  wire [9:0] dout1_1;
  (* src = "src/SRAM_MEM.v:27.7-27.15" *)
  wire dout_sel;
  INV_X1 _04_ (
    .A(csb1),
    .ZN(_01_)
  );
  INV_X1 _05_ (
    .A(csb0),
    .ZN(_02_)
  );
  MUX2_X1 _06_ (
    .A(dout1_0[8]),
    .B(dout1_1[8]),
    .S(dout_sel),
    .Z(dout1[8])
  );
  MUX2_X1 _07_ (
    .A(dout1_0[7]),
    .B(dout1_1[7]),
    .S(dout_sel),
    .Z(dout1[7])
  );
  MUX2_X1 _08_ (
    .A(dout1_0[6]),
    .B(dout1_1[6]),
    .S(dout_sel),
    .Z(dout1[6])
  );
  MUX2_X1 _09_ (
    .A(dout1_0[5]),
    .B(dout1_1[5]),
    .S(dout_sel),
    .Z(dout1[5])
  );
  MUX2_X1 _10_ (
    .A(dout1_0[4]),
    .B(dout1_1[4]),
    .S(dout_sel),
    .Z(dout1[4])
  );
  MUX2_X1 _11_ (
    .A(dout1_0[3]),
    .B(dout1_1[3]),
    .S(dout_sel),
    .Z(dout1[3])
  );
  MUX2_X1 _12_ (
    .A(dout1_0[2]),
    .B(dout1_1[2]),
    .S(dout_sel),
    .Z(dout1[2])
  );
  MUX2_X1 _13_ (
    .A(dout1_0[1]),
    .B(dout1_1[1]),
    .S(dout_sel),
    .Z(dout1[1])
  );
  MUX2_X1 _14_ (
    .A(dout1_0[0]),
    .B(dout1_1[0]),
    .S(dout_sel),
    .Z(dout1[0])
  );
  MUX2_X1 _15_ (
    .A(dout1_0[9]),
    .B(dout1_1[9]),
    .S(dout_sel),
    .Z(dout1[9])
  );
  NAND2_X1 _16_ (
    .A1(_01_),
    .A2(addr1[10]),
    .ZN(csb1_1)
  );
  OR2_X1 _17_ (
    .A1(csb1),
    .A2(addr1[10]),
    .ZN(csb1_0)
  );
  NAND2_X1 _18_ (
    .A1(_02_),
    .A2(addr0[10]),
    .ZN(csb0_1)
  );
  OR2_X1 _19_ (
    .A1(csb0),
    .A2(addr0[10]),
    .ZN(csb0_0)
  );
  MUX2_X1 _20_ (
    .A(addr1[10]),
    .B(dout_sel),
    .S(csb1),
    .Z(_00_)
  );
  (* src = "src/SRAM_MEM.v:28.3-30.6" *)
  DFF_X1 _21_ (
    .CK(clk1),
    .D(_00_),
    .Q(dout_sel),
    .QN(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/SRAM_MEM.v:34.8-43.4" *)
  SRAM sram0 (
    .addr0(addr0[9:0]),
    .addr1(addr1[9:0]),
    .clk0(clk0),
    .clk1(clk1),
    .csb0(csb0_0),
    .csb1(csb1_0),
    .din0(din0),
    .dout1(dout1_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/SRAM_MEM.v:45.8-54.4" *)
  SRAM sram1 (
    .addr0(addr0[9:0]),
    .addr1(addr1[9:0]),
    .clk0(clk0),
    .clk1(clk1),
    .csb0(csb0_1),
    .csb1(csb1_1),
    .din0(din0),
    .dout1(dout1_1)
  );
endmodule
