/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/C_CPU.v:1.1-65.10" *)
module C_CPU(clk, resetn, coef_in, valid_in, h_sync, v_sync, red_in, green_in, blue_in, gam_red_in, gam_green_in, gam_blue_in, row0, row1, row2, valid_out, h_sync_out, v_sync_out, red_out, green_out, blue_out
);
  (* src = "src/C_CPU.v:9.11-9.14" *)
  input clk;
  wire clk;
  (* src = "src/C_CPU.v:9.16-9.22" *)
  input resetn;
  wire resetn;
  (* src = "src/C_CPU.v:9.24-9.31" *)
  input coef_in;
  wire coef_in;
  (* src = "src/C_CPU.v:10.11-10.19" *)
  input valid_in;
  wire valid_in;
  (* src = "src/C_CPU.v:10.21-10.27" *)
  input h_sync;
  wire h_sync;
  (* src = "src/C_CPU.v:10.29-10.35" *)
  input v_sync;
  wire v_sync;
  (* src = "src/C_CPU.v:11.24-11.30" *)
  input [9:0] red_in;
  wire [9:0] red_in;
  (* src = "src/C_CPU.v:11.32-11.40" *)
  input [9:0] green_in;
  wire [9:0] green_in;
  (* src = "src/C_CPU.v:11.42-11.49" *)
  input [9:0] blue_in;
  wire [9:0] blue_in;
  (* src = "src/C_CPU.v:12.24-12.34" *)
  input [9:0] gam_red_in;
  wire [9:0] gam_red_in;
  (* src = "src/C_CPU.v:12.36-12.48" *)
  input [9:0] gam_green_in;
  wire [9:0] gam_green_in;
  (* src = "src/C_CPU.v:12.50-12.61" *)
  input [9:0] gam_blue_in;
  wire [9:0] gam_blue_in;
  (* src = "src/C_CPU.v:13.27-13.31" *)
  input [29:0] row0;
  wire [29:0] row0;
  (* src = "src/C_CPU.v:13.33-13.37" *)
  input [29:0] row1;
  wire [29:0] row1;
  (* src = "src/C_CPU.v:13.39-13.43" *)
  input [29:0] row2;
  wire [29:0] row2;
  (* src = "src/C_CPU.v:14.12-14.21" *)
  output valid_out;
  wire valid_out;
  (* src = "src/C_CPU.v:14.23-14.33" *)
  output h_sync_out;
  wire h_sync_out;
  (* src = "src/C_CPU.v:14.35-14.45" *)
  output v_sync_out;
  wire v_sync_out;
  (* src = "src/C_CPU.v:15.25-15.32" *)
  output [9:0] red_out;
  wire [9:0] red_out;
  (* src = "src/C_CPU.v:15.34-15.43" *)
  output [9:0] green_out;
  wire [9:0] green_out;
  (* src = "src/C_CPU.v:15.45-15.53" *)
  output [9:0] blue_out;
  wire [9:0] blue_out;
  (* src = "src/C_CPU.v:19.55-19.69" *)
  wire [9:0] blue_ccm_gamma;
  (* src = "src/C_CPU.v:19.38-19.53" *)
  wire [9:0] green_ccm_gamma;
  (* src = "src/C_CPU.v:18.27-18.38" *)
  wire h_ccm_gamma;
  (* src = "src/C_CPU.v:19.23-19.36" *)
  wire [9:0] red_ccm_gamma;
  (* src = "src/C_CPU.v:18.40-18.51" *)
  wire v_ccm_gamma;
  (* src = "src/C_CPU.v:18.10-18.25" *)
  wire valid_ccm_gamma;
  (* module_not_derived = 32'd1 *)
  (* src = "src/C_CPU.v:22.9-41.6" *)
  CCM ccm (
    .blue_in(blue_in),
    .blue_out(blue_ccm_gamma),
    .clk(clk),
    .coef_in(coef_in),
    .green_in(green_in),
    .green_out(green_ccm_gamma),
    .h_sync(h_sync),
    .h_sync_out(h_ccm_gamma),
    .red_in(red_in),
    .red_out(red_ccm_gamma),
    .resetn(resetn),
    .row0(row0),
    .row1(row1),
    .row2(row2),
    .v_sync(v_sync),
    .v_sync_out(v_ccm_gamma),
    .valid_in(valid_in),
    .valid_out(valid_ccm_gamma)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/C_CPU.v:44.9-62.6" *)
  GAM gam (
    .blue_in(blue_ccm_gamma),
    .blue_out(blue_out),
    .clk(clk),
    .gam_blue_in(gam_blue_in),
    .gam_green_in(gam_green_in),
    .gam_red_in(gam_red_in),
    .green_in(green_ccm_gamma),
    .green_out(green_out),
    .h_sync(h_ccm_gamma),
    .h_sync_out(h_sync_out),
    .red_in(red_ccm_gamma),
    .red_out(red_out),
    .resetn(resetn),
    .v_sync(v_ccm_gamma),
    .v_sync_out(v_sync_out),
    .valid_in(valid_ccm_gamma),
    .valid_out(valid_out)
  );
endmodule
