/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/D_CPU.v:1.1-79.10" *)
module D_CPU(clk, resetn, valid_in, h_sync, v_sync, pixel_in, valid_out, h_sync_out, v_sync_out, red_out, green_out, blue_out);
  (* src = "src/D_CPU.v:12.11-12.14" *)
  input clk;
  wire clk;
  (* src = "src/D_CPU.v:12.16-12.22" *)
  input resetn;
  wire resetn;
  (* src = "src/D_CPU.v:13.11-13.19" *)
  input valid_in;
  wire valid_in;
  (* src = "src/D_CPU.v:13.21-13.27" *)
  input h_sync;
  wire h_sync;
  (* src = "src/D_CPU.v:13.29-13.35" *)
  input v_sync;
  wire v_sync;
  (* src = "src/D_CPU.v:14.24-14.32" *)
  input [9:0] pixel_in;
  wire [9:0] pixel_in;
  (* src = "src/D_CPU.v:15.12-15.21" *)
  output valid_out;
  wire valid_out;
  (* src = "src/D_CPU.v:15.23-15.33" *)
  output h_sync_out;
  wire h_sync_out;
  (* src = "src/D_CPU.v:15.35-15.45" *)
  output v_sync_out;
  wire v_sync_out;
  (* src = "src/D_CPU.v:16.25-16.32" *)
  output [9:0] red_out;
  wire [9:0] red_out;
  (* src = "src/D_CPU.v:16.34-16.43" *)
  output [9:0] green_out;
  wire [9:0] green_out;
  (* src = "src/D_CPU.v:16.45-16.53" *)
  output [9:0] blue_out;
  wire [9:0] blue_out;
  (* src = "src/D_CPU.v:26.55-26.69" *)
  wire [9:0] blue_demos_out;
  (* src = "src/D_CPU.v:26.38-26.53" *)
  wire [9:0] green_demos_out;
  (* src = "src/D_CPU.v:19.25-19.34" *)
  wire h_bnr_wbg;
  (* src = "src/D_CPU.v:25.27-25.38" *)
  wire h_demos_out;
  (* src = "src/D_CPU.v:22.27-22.38" *)
  wire h_wbg_demos;
  (* src = "src/D_CPU.v:20.23-20.36" *)
  wire [9:0] pixel_bnr_wbg;
  (* src = "src/D_CPU.v:23.23-23.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9" *)
  wire [9:0] pixel_wbg_demos;
  (* src = "src/D_CPU.v:26.23-26.36" *)
  wire [9:0] red_demos_out;
  (* src = "src/D_CPU.v:19.36-19.45" *)
  wire v_bnr_wbg;
  (* src = "src/D_CPU.v:25.40-25.51" *)
  wire v_demos_out;
  (* src = "src/D_CPU.v:22.40-22.51" *)
  wire v_wbg_demos;
  (* src = "src/D_CPU.v:19.10-19.23" *)
  wire valid_bnr_wbg;
  (* src = "src/D_CPU.v:25.10-25.25" *)
  wire valid_demos_out;
  (* src = "src/D_CPU.v:22.10-22.25" *)
  wire valid_wbg_demos;
  (* module_not_derived = 32'd1 *)
  (* src = "src/D_CPU.v:35.10-46.6" *)
  BNR bnr (
    .clk(clk),
    .h_sync(h_sync),
    .h_sync_out(h_bnr_wbg),
    .pixel_in(pixel_in),
    .pixel_out(pixel_bnr_wbg),
    .resetn(resetn),
    .v_sync(v_sync),
    .v_sync_out(v_bnr_wbg),
    .valid_in(valid_in),
    .valid_out(valid_bnr_wbg)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/D_CPU.v:63.14-76.6" *)
  DEMOSAIC demos (
    .blue_out(blue_demos_out),
    .clk(clk),
    .green_out(green_demos_out),
    .h_sync(h_wbg_demos),
    .h_sync_out(h_demos_out),
    .pixel_in(pixel_in),
    .red_out(red_demos_out),
    .resetn(resetn),
    .v_sync(v_wbg_demos),
    .v_sync_out(v_demos_out),
    .valid_in(valid_wbg_demos),
    .valid_out(valid_demos_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/D_CPU.v:49.9-60.6" *)
  WBG wbg (
    .clk(clk),
    .h_sync(h_bnr_wbg),
    .h_sync_out(h_wbg_demos),
    .pixel_in(pixel_bnr_wbg),
    .pixel_out(pixel_wbg_demos),
    .resetn(resetn),
    .v_sync(v_bnr_wbg),
    .v_sync_out(v_wbg_demos),
    .valid_in(valid_bnr_wbg),
    .valid_out(valid_wbg_demos)
  );
  assign blue_out = blue_demos_out;
  assign green_out = green_demos_out;
  assign red_out = red_demos_out;
  assign v_sync_out = v_demos_out;
  assign h_sync_out = h_demos_out;
  assign valid_out = valid_demos_out;
endmodule
