/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/SRAM_MEM.v:1.1-29.10" *)
module SRAM(clk0, csb0, addr0, din0, clk1, csb1, addr1, dout1);
  (* src = "src/SRAM_MEM.v:8.9-8.13" *)
  input clk0;
  wire clk0;
  (* src = "src/SRAM_MEM.v:9.9-9.13" *)
  input csb0;
  wire csb0;
  (* src = "src/SRAM_MEM.v:10.27-10.32" *)
  input [9:0] addr0;
  wire [9:0] addr0;
  (* src = "src/SRAM_MEM.v:11.27-11.31" *)
  input [9:0] din0;
  wire [9:0] din0;
  (* src = "src/SRAM_MEM.v:12.9-12.13" *)
  input clk1;
  wire clk1;
  (* src = "src/SRAM_MEM.v:13.9-13.13" *)
  input csb1;
  wire csb1;
  (* src = "src/SRAM_MEM.v:14.27-14.32" *)
  input [9:0] addr1;
  wire [9:0] addr1;
  (* src = "src/SRAM_MEM.v:15.26-15.31" *)
  output [9:0] dout1;
  wire [9:0] dout1;
  (* module_not_derived = 32'd1 *)
  (* src = "src/SRAM_MEM.v:18.19-27.6" *)
  sram_10x1024 sram (
    .addr0(addr0),
    .addr1(addr1),
    .clk0(clk0),
    .clk1(clk1),
    .csb0(csb0),
    .csb1(csb1),
    .din0(din0),
    .dout1(dout1)
  );
endmodule
