/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/P_CPU.v:1.1-80.10" *)
module P_CPU(clk, resetn, valid_in, h_sync, v_sync, pixel_in, valid_out, h_sync_out, v_sync_out, pixel_out);
  (* src = "src/P_CPU.v:16.11-16.14" *)
  input clk;
  wire clk;
  (* src = "src/P_CPU.v:16.16-16.22" *)
  input resetn;
  wire resetn;
  (* src = "src/P_CPU.v:17.11-17.19" *)
  input valid_in;
  wire valid_in;
  (* src = "src/P_CPU.v:17.21-17.27" *)
  input h_sync;
  wire h_sync;
  (* src = "src/P_CPU.v:17.29-17.35" *)
  input v_sync;
  wire v_sync;
  (* src = "src/P_CPU.v:18.24-18.32" *)
  input [9:0] pixel_in;
  wire [9:0] pixel_in;
  (* src = "src/P_CPU.v:19.12-19.21" *)
  output valid_out;
  wire valid_out;
  (* src = "src/P_CPU.v:19.23-19.33" *)
  output h_sync_out;
  wire h_sync_out;
  (* src = "src/P_CPU.v:19.35-19.45" *)
  output v_sync_out;
  wire v_sync_out;
  (* src = "src/P_CPU.v:20.25-20.34" *)
  output [9:0] pixel_out;
  wire [9:0] pixel_out;
  (* src = "src/P_CPU.v:23.25-23.34" *)
  wire h_blc_lsc;
  (* src = "src/P_CPU.v:29.25-29.34" *)
  wire h_dpc_out;
  (* src = "src/P_CPU.v:26.25-26.34" *)
  wire h_lsc_dpc;
  (* src = "src/P_CPU.v:24.23-24.36" *)
  wire [9:0] pixel_blc_lsc;
  (* src = "src/P_CPU.v:30.23-30.36" *)
  wire [9:0] pixel_dpc_out;
  (* src = "src/P_CPU.v:27.23-27.36" *)
  wire [9:0] pixel_lsc_dpc;
  (* src = "src/P_CPU.v:23.36-23.45" *)
  wire v_blc_lsc;
  (* src = "src/P_CPU.v:29.36-29.45" *)
  wire v_dpc_out;
  (* src = "src/P_CPU.v:26.36-26.45" *)
  wire v_lsc_dpc;
  (* src = "src/P_CPU.v:23.10-23.23" *)
  wire valid_blc_lsc;
  (* src = "src/P_CPU.v:29.10-29.23" *)
  wire valid_dpc_out;
  (* src = "src/P_CPU.v:26.10-26.23" *)
  wire valid_lsc_dpc;
  (* module_not_derived = 32'd1 *)
  (* src = "src/P_CPU.v:38.9-49.6" *)
  BLC blc (
    .clk(clk),
    .h_sync(h_sync),
    .h_sync_out(h_blc_lsc),
    .pixel_in(pixel_in),
    .pixel_out(pixel_blc_lsc),
    .resetn(resetn),
    .v_sync(v_sync),
    .v_sync_out(v_blc_lsc),
    .valid_in(valid_in),
    .valid_out(valid_blc_lsc)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/P_CPU.v:66.9-77.6" *)
  DPC dpc (
    .clk(clk),
    .h_sync(h_lsc_dpc),
    .h_sync_out(h_dpc_out),
    .pixel_in(pixel_lsc_dpc),
    .pixel_out(pixel_dpc_out),
    .resetn(resetn),
    .v_sync(v_lsc_dpc),
    .v_sync_out(v_dpc_out),
    .valid_in(valid_lsc_dpc),
    .valid_out(valid_dpc_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/P_CPU.v:52.9-63.6" *)
  LSC lsc (
    .clk(clk),
    .h_sync(h_blc_lsc),
    .h_sync_out(h_lsc_dpc),
    .pixel_in(pixel_blc_lsc),
    .pixel_out(pixel_lsc_dpc),
    .resetn(resetn),
    .v_sync(v_blc_lsc),
    .v_sync_out(v_lsc_dpc),
    .valid_in(valid_blc_lsc),
    .valid_out(valid_lsc_dpc)
  );
  assign pixel_out = pixel_dpc_out;
  assign v_sync_out = v_dpc_out;
  assign h_sync_out = h_dpc_out;
  assign valid_out = valid_dpc_out;
endmodule
