/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/ISP.v:1.1-95.10" *)
module ISP(clk, resetn, coef_in, valid_in, h_sync, v_sync, pixel_in, gam_red_in, gam_green_in, gam_blue_in, row0, row1, row2, valid_out, h_sync_out, v_sync_out, red_out, green_out, blue_out);
  (* src = "src/ISP.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "src/ISP.v:5.16-5.22" *)
  input resetn;
  wire resetn;
  (* src = "src/ISP.v:5.24-5.31" *)
  input coef_in;
  wire coef_in;
  (* src = "src/ISP.v:6.11-6.19" *)
  input valid_in;
  wire valid_in;
  (* src = "src/ISP.v:6.21-6.27" *)
  input h_sync;
  wire h_sync;
  (* src = "src/ISP.v:6.29-6.35" *)
  input v_sync;
  wire v_sync;
  (* src = "src/ISP.v:7.24-7.32" *)
  input [9:0] pixel_in;
  wire [9:0] pixel_in;
  (* src = "src/ISP.v:8.24-8.34" *)
  input [9:0] gam_red_in;
  wire [9:0] gam_red_in;
  (* src = "src/ISP.v:8.36-8.48" *)
  input [9:0] gam_green_in;
  wire [9:0] gam_green_in;
  (* src = "src/ISP.v:8.50-8.61" *)
  input [9:0] gam_blue_in;
  wire [9:0] gam_blue_in;
  (* src = "src/ISP.v:9.27-9.31" *)
  input [29:0] row0;
  wire [29:0] row0;
  (* src = "src/ISP.v:9.33-9.37" *)
  input [29:0] row1;
  wire [29:0] row1;
  (* src = "src/ISP.v:9.39-9.43" *)
  input [29:0] row2;
  wire [29:0] row2;
  (* src = "src/ISP.v:10.12-10.21" *)
  output valid_out;
  wire valid_out;
  (* src = "src/ISP.v:10.23-10.33" *)
  output h_sync_out;
  wire h_sync_out;
  (* src = "src/ISP.v:10.35-10.45" *)
  output v_sync_out;
  wire v_sync_out;
  (* src = "src/ISP.v:11.25-11.32" *)
  output [9:0] red_out;
  wire [9:0] red_out;
  (* src = "src/ISP.v:11.34-11.43" *)
  output [9:0] green_out;
  wire [9:0] green_out;
  (* src = "src/ISP.v:11.45-11.53" *)
  output [9:0] blue_out;
  wire [9:0] blue_out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "src/ISP.v:21.43-21.51" *)
  wire [9:0] blue_d_c;
  (* src = "src/ISP.v:21.32-21.41" *)
  wire [9:0] green_d_c;
  (* src = "src/ISP.v:20.21-20.26" *)
  wire h_d_c;
  (* src = "src/ISP.v:14.21-14.26" *)
  wire h_p_d;
  (* src = "src/ISP.v:15.23-15.32" *)
  wire [9:0] pixel_p_d;
  (* src = "src/ISP.v:21.23-21.30" *)
  wire [9:0] red_d_c;
  (* src = "src/ISP.v:17.25-17.34" *)
  wire reg_h_p_d;
  (* src = "src/ISP.v:18.23-18.36" *)
  wire [9:0] reg_pixel_p_d;
  (* src = "src/ISP.v:17.36-17.45" *)
  wire reg_v_p_d;
  (* src = "src/ISP.v:17.10-17.23" *)
  wire reg_valid_p_d;
  (* src = "src/ISP.v:20.28-20.33" *)
  wire v_d_c;
  (* src = "src/ISP.v:14.28-14.33" *)
  wire v_p_d;
  (* src = "src/ISP.v:20.10-20.19" *)
  wire valid_d_c;
  (* src = "src/ISP.v:14.10-14.19" *)
  wire valid_p_d;
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _13_ (
    .CK(clk),
    .D(v_p_d),
    .Q(reg_v_p_d),
    .QN(_11_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _14_ (
    .CK(clk),
    .D(pixel_p_d[0]),
    .Q(reg_pixel_p_d[0]),
    .QN(_09_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _15_ (
    .CK(clk),
    .D(pixel_p_d[1]),
    .Q(reg_pixel_p_d[1]),
    .QN(_08_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _16_ (
    .CK(clk),
    .D(pixel_p_d[2]),
    .Q(reg_pixel_p_d[2]),
    .QN(_07_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _17_ (
    .CK(clk),
    .D(pixel_p_d[3]),
    .Q(reg_pixel_p_d[3]),
    .QN(_06_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _18_ (
    .CK(clk),
    .D(pixel_p_d[4]),
    .Q(reg_pixel_p_d[4]),
    .QN(_05_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _19_ (
    .CK(clk),
    .D(pixel_p_d[5]),
    .Q(reg_pixel_p_d[5]),
    .QN(_04_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _20_ (
    .CK(clk),
    .D(pixel_p_d[6]),
    .Q(reg_pixel_p_d[6]),
    .QN(_03_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _21_ (
    .CK(clk),
    .D(pixel_p_d[7]),
    .Q(reg_pixel_p_d[7]),
    .QN(_02_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _22_ (
    .CK(clk),
    .D(pixel_p_d[8]),
    .Q(reg_pixel_p_d[8]),
    .QN(_01_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _23_ (
    .CK(clk),
    .D(pixel_p_d[9]),
    .Q(reg_pixel_p_d[9]),
    .QN(_12_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _24_ (
    .CK(clk),
    .D(valid_p_d),
    .Q(reg_valid_p_d),
    .QN(_10_),
    .RN(resetn)
  );
  (* src = "src/ISP.v:23.5-38.8" *)
  DFFR_X1 _25_ (
    .CK(clk),
    .D(h_p_d),
    .Q(reg_h_p_d),
    .QN(_00_),
    .RN(resetn)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/ISP.v:68.11-90.6" *)
  C_CPU c_cpu (
    .blue_in(blue_d_c),
    .blue_out(blue_out),
    .clk(clk),
    .coef_in(coef_in),
    .gam_blue_in(gam_blue_in),
    .gam_green_in(gam_green_in),
    .gam_red_in(gam_red_in),
    .green_in(green_d_c),
    .green_out(green_out),
    .h_sync(h_d_c),
    .h_sync_out(h_sync_out),
    .red_in(red_d_c),
    .red_out(red_out),
    .resetn(resetn),
    .row0(row0),
    .row1(row1),
    .row2(row2),
    .v_sync(v_d_c),
    .v_sync_out(v_sync_out),
    .valid_in(valid_d_c),
    .valid_out(valid_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/ISP.v:53.11-66.6" *)
  D_CPU d_cpu (
    .blue_out(blue_d_c),
    .clk(clk),
    .green_out(green_d_c),
    .h_sync(reg_h_p_d),
    .h_sync_out(h_d_c),
    .pixel_in(reg_pixel_p_d),
    .red_out(red_d_c),
    .resetn(resetn),
    .v_sync(reg_v_p_d),
    .v_sync_out(v_d_c),
    .valid_in(reg_valid_p_d),
    .valid_out(valid_d_c)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/ISP.v:40.11-51.6" *)
  P_CPU p_cpu (
    .clk(clk),
    .h_sync(h_sync),
    .h_sync_out(h_p_d),
    .pixel_in(pixel_in),
    .pixel_out(pixel_p_d),
    .resetn(resetn),
    .v_sync(v_sync),
    .v_sync_out(v_p_d),
    .valid_in(valid_in),
    .valid_out(valid_p_d)
  );
endmodule
