/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/WBG.v:1.1-83.10" *)
module WBG(clk, resetn, valid_in, v_sync, h_sync, pixel_in, valid_out, v_sync_out, h_sync_out, pixel_out);
  (* src = "src/WBG.v:11.11-11.14" *)
  input clk;
  wire clk;
  (* src = "src/WBG.v:11.16-11.22" *)
  input resetn;
  wire resetn;
  (* src = "src/WBG.v:12.11-12.19" *)
  input valid_in;
  wire valid_in;
  (* src = "src/WBG.v:12.21-12.27" *)
  input v_sync;
  wire v_sync;
  (* src = "src/WBG.v:12.29-12.35" *)
  input h_sync;
  wire h_sync;
  (* src = "src/WBG.v:13.24-13.32" *)
  input [9:0] pixel_in;
  wire [9:0] pixel_in;
  (* src = "src/WBG.v:14.16-14.25" *)
  output valid_out;
  wire valid_out;
  (* src = "src/WBG.v:14.27-14.37" *)
  output v_sync_out;
  wire v_sync_out;
  (* src = "src/WBG.v:14.39-14.49" *)
  output h_sync_out;
  wire h_sync_out;
  (* src = "src/WBG.v:15.29-15.38" *)
  output [9:0] pixel_out;
  wire [9:0] pixel_out;
  (* src = "src/WBG.v:21.5-38.8" *)
  wire _000_;
  (* src = "src/WBG.v:21.5-38.8" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  (* src = "src/WBG.v:20.14-20.17" *)
  wire _129_;
  (* src = "src/WBG.v:12.29-12.35" *)
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _225_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _226_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _227_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _228_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _229_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _230_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _231_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _232_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _233_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _234_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _235_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _236_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _237_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _238_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _239_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _240_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _241_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _242_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _243_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _244_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _245_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _246_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _247_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _248_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _249_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _250_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _251_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _252_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _253_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _254_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _255_;
  (* src = "src/WBG.v:20.9-20.12" *)
  wire _256_;
  (* src = "src/WBG.v:12.21-12.27" *)
  wire _257_;
  (* src = "src/WBG.v:12.11-12.19" *)
  wire _258_;
  (* src = "src/WBG.v:40.20-40.30" *)
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  (* force_downto = 32'd1 *)
  (* src = "src/WBG.v:67.59-67.59|src/WBG.v:64.17-69.24|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" *)
  (* unused_bits = "0" *)
  wire [11:0] _322_;
  (* src = "src/WBG.v:20.14-20.17" *)
  wire col;
  (* src = "src/WBG.v:40.32-40.38" *)
  wire [0:0] h_pipe;
  (* src = "src/WBG.v:41.40-41.48" *)
  (* unused_bits = "7" *)
  wire [21:0] res_pipe;
  (* src = "src/WBG.v:20.9-20.12" *)
  wire row;
  (* src = "src/WBG.v:40.40-40.46" *)
  wire [0:0] v_pipe;
  (* src = "src/WBG.v:40.20-40.30" *)
  wire [0:0] valid_pipe;
  INV_X1 _323_ (
    .A(_225_),
    .ZN(_187_)
  );
  INV_X1 _324_ (
    .A(_233_),
    .ZN(_188_)
  );
  INV_X1 _325_ (
    .A(_232_),
    .ZN(_189_)
  );
  INV_X1 _326_ (
    .A(_228_),
    .ZN(_190_)
  );
  INV_X1 _327_ (
    .A(_253_),
    .ZN(_191_)
  );
  INV_X1 _328_ (
    .A(_258_),
    .ZN(_192_)
  );
  NAND2_X1 _329_ (
    .A1(_191_),
    .A2(_259_),
    .ZN(_193_)
  );
  OAI22_X1 _330_ (
    .A1(_241_),
    .A2(_259_),
    .B1(_193_),
    .B2(_249_),
    .ZN(_194_)
  );
  INV_X1 _331_ (
    .A(_194_),
    .ZN(_106_)
  );
  AND2_X1 _332_ (
    .A1(_256_),
    .A2(_129_),
    .ZN(_195_)
  );
  NOR2_X1 _333_ (
    .A1(_233_),
    .A2(_234_),
    .ZN(_196_)
  );
  NAND2_X1 _334_ (
    .A1(_233_),
    .A2(_232_),
    .ZN(_197_)
  );
  XNOR2_X1 _335_ (
    .A(_233_),
    .B(_232_),
    .ZN(_198_)
  );
  AND2_X1 _336_ (
    .A1(_232_),
    .A2(_231_),
    .ZN(_199_)
  );
  NOR2_X1 _337_ (
    .A1(_232_),
    .A2(_231_),
    .ZN(_200_)
  );
  AND2_X1 _338_ (
    .A1(_231_),
    .A2(_230_),
    .ZN(_201_)
  );
  NAND2_X1 _339_ (
    .A1(_231_),
    .A2(_230_),
    .ZN(_202_)
  );
  OR2_X1 _340_ (
    .A1(_231_),
    .A2(_230_),
    .ZN(_203_)
  );
  NAND2_X1 _341_ (
    .A1(_202_),
    .A2(_203_),
    .ZN(_204_)
  );
  AND2_X1 _342_ (
    .A1(_230_),
    .A2(_229_),
    .ZN(_205_)
  );
  NOR2_X1 _343_ (
    .A1(_230_),
    .A2(_229_),
    .ZN(_206_)
  );
  NAND2_X1 _344_ (
    .A1(_228_),
    .A2(_229_),
    .ZN(_207_)
  );
  XNOR2_X1 _345_ (
    .A(_228_),
    .B(_229_),
    .ZN(_208_)
  );
  AOI21_X1 _346_ (
    .A(_227_),
    .B1(_226_),
    .B2(_225_),
    .ZN(_209_)
  );
  AOI21_X1 _347_ (
    .A(_228_),
    .B1(_227_),
    .B2(_226_),
    .ZN(_210_)
  );
  NOR2_X1 _348_ (
    .A1(_209_),
    .A2(_210_),
    .ZN(_211_)
  );
  OR3_X1 _349_ (
    .A1(_208_),
    .A2(_209_),
    .A3(_210_),
    .ZN(_212_)
  );
  NAND2_X1 _350_ (
    .A1(_207_),
    .A2(_212_),
    .ZN(_213_)
  );
  AOI21_X1 _351_ (
    .A(_206_),
    .B1(_207_),
    .B2(_212_),
    .ZN(_214_)
  );
  NOR2_X1 _352_ (
    .A1(_205_),
    .A2(_214_),
    .ZN(_215_)
  );
  OR2_X1 _353_ (
    .A1(_205_),
    .A2(_214_),
    .ZN(_216_)
  );
  OAI21_X1 _354_ (
    .A(_202_),
    .B1(_204_),
    .B2(_215_),
    .ZN(_217_)
  );
  AOI211_X1 _355_ (
    .A(_199_),
    .B(_201_),
    .C1(_203_),
    .C2(_216_),
    .ZN(_218_)
  );
  OR3_X1 _356_ (
    .A1(_198_),
    .A2(_200_),
    .A3(_218_),
    .ZN(_219_)
  );
  OAI21_X1 _357_ (
    .A(_233_),
    .B1(_234_),
    .B2(_232_),
    .ZN(_220_)
  );
  OAI21_X1 _358_ (
    .A(_220_),
    .B1(_219_),
    .B2(_196_),
    .ZN(_221_)
  );
  NOR2_X1 _359_ (
    .A1(_195_),
    .A2(_221_),
    .ZN(_222_)
  );
  NOR2_X1 _360_ (
    .A1(_256_),
    .A2(_129_),
    .ZN(_223_)
  );
  OR2_X1 _361_ (
    .A1(_256_),
    .A2(_129_),
    .ZN(_224_)
  );
  NOR2_X1 _362_ (
    .A1(_195_),
    .A2(_223_),
    .ZN(_131_)
  );
  OAI211_X1 _363_ (
    .A(_234_),
    .B(_258_),
    .C1(_195_),
    .C2(_223_),
    .ZN(_132_)
  );
  OAI22_X1 _364_ (
    .A1(_191_),
    .A2(_258_),
    .B1(_222_),
    .B2(_132_),
    .ZN(_107_)
  );
  OAI22_X1 _365_ (
    .A1(_259_),
    .A2(_244_),
    .B1(_193_),
    .B2(_252_),
    .ZN(_133_)
  );
  INV_X1 _366_ (
    .A(_133_),
    .ZN(_108_)
  );
  OAI22_X1 _367_ (
    .A1(_259_),
    .A2(_240_),
    .B1(_193_),
    .B2(_248_),
    .ZN(_134_)
  );
  INV_X1 _368_ (
    .A(_134_),
    .ZN(_109_)
  );
  OAI22_X1 _369_ (
    .A1(_259_),
    .A2(_239_),
    .B1(_193_),
    .B2(_247_),
    .ZN(_135_)
  );
  INV_X1 _370_ (
    .A(_135_),
    .ZN(_110_)
  );
  OAI22_X1 _371_ (
    .A1(_259_),
    .A2(_238_),
    .B1(_193_),
    .B2(_246_),
    .ZN(_136_)
  );
  INV_X1 _372_ (
    .A(_136_),
    .ZN(_111_)
  );
  OAI22_X1 _373_ (
    .A1(_259_),
    .A2(_237_),
    .B1(_193_),
    .B2(_245_),
    .ZN(_137_)
  );
  INV_X1 _374_ (
    .A(_137_),
    .ZN(_112_)
  );
  OAI22_X1 _375_ (
    .A1(_259_),
    .A2(_236_),
    .B1(_193_),
    .B2(_255_),
    .ZN(_138_)
  );
  INV_X1 _376_ (
    .A(_138_),
    .ZN(_113_)
  );
  OAI22_X1 _377_ (
    .A1(_259_),
    .A2(_235_),
    .B1(_193_),
    .B2(_254_),
    .ZN(_139_)
  );
  INV_X1 _378_ (
    .A(_139_),
    .ZN(_114_)
  );
  OAI22_X1 _379_ (
    .A1(_259_),
    .A2(_243_),
    .B1(_193_),
    .B2(_251_),
    .ZN(_140_)
  );
  INV_X1 _380_ (
    .A(_140_),
    .ZN(_115_)
  );
  OAI22_X1 _381_ (
    .A1(_259_),
    .A2(_242_),
    .B1(_193_),
    .B2(_250_),
    .ZN(_141_)
  );
  INV_X1 _382_ (
    .A(_141_),
    .ZN(_116_)
  );
  NOR2_X1 _383_ (
    .A1(_258_),
    .A2(_252_),
    .ZN(_142_)
  );
  AOI211_X1 _384_ (
    .A(_188_),
    .B(_234_),
    .C1(_189_),
    .C2(_219_),
    .ZN(_143_)
  );
  AND3_X1 _385_ (
    .A1(_188_),
    .A2(_234_),
    .A3(_219_),
    .ZN(_144_)
  );
  OAI21_X1 _386_ (
    .A(_223_),
    .B1(_143_),
    .B2(_144_),
    .ZN(_145_)
  );
  AOI221_X1 _387_ (
    .A(_192_),
    .B1(_195_),
    .B2(_233_),
    .C1(_131_),
    .C2(_234_),
    .ZN(_146_)
  );
  AOI21_X1 _388_ (
    .A(_142_),
    .B1(_145_),
    .B2(_146_),
    .ZN(_117_)
  );
  NOR2_X1 _389_ (
    .A1(_251_),
    .A2(_258_),
    .ZN(_147_)
  );
  XOR2_X1 _390_ (
    .A(_233_),
    .B(_234_),
    .Z(_148_)
  );
  AND3_X1 _391_ (
    .A1(_197_),
    .A2(_219_),
    .A3(_148_),
    .ZN(_149_)
  );
  AOI21_X1 _392_ (
    .A(_148_),
    .B1(_219_),
    .B2(_197_),
    .ZN(_150_)
  );
  OAI21_X1 _393_ (
    .A(_223_),
    .B1(_149_),
    .B2(_150_),
    .ZN(_151_)
  );
  AOI221_X1 _394_ (
    .A(_192_),
    .B1(_195_),
    .B2(_232_),
    .C1(_131_),
    .C2(_233_),
    .ZN(_152_)
  );
  AOI21_X1 _395_ (
    .A(_147_),
    .B1(_151_),
    .B2(_152_),
    .ZN(_118_)
  );
  NOR2_X1 _396_ (
    .A1(_250_),
    .A2(_258_),
    .ZN(_153_)
  );
  OAI21_X1 _397_ (
    .A(_198_),
    .B1(_200_),
    .B2(_218_),
    .ZN(_154_)
  );
  NAND3_X1 _398_ (
    .A1(_219_),
    .A2(_223_),
    .A3(_154_),
    .ZN(_155_)
  );
  AOI221_X1 _399_ (
    .A(_192_),
    .B1(_195_),
    .B2(_231_),
    .C1(_131_),
    .C2(_232_),
    .ZN(_156_)
  );
  AOI21_X1 _400_ (
    .A(_153_),
    .B1(_155_),
    .B2(_156_),
    .ZN(_119_)
  );
  NOR2_X1 _401_ (
    .A1(_249_),
    .A2(_258_),
    .ZN(_157_)
  );
  OR2_X1 _402_ (
    .A1(_199_),
    .A2(_200_),
    .ZN(_158_)
  );
  XNOR2_X1 _403_ (
    .A(_217_),
    .B(_158_),
    .ZN(_159_)
  );
  NAND2_X1 _404_ (
    .A1(_223_),
    .A2(_159_),
    .ZN(_160_)
  );
  AOI221_X1 _405_ (
    .A(_192_),
    .B1(_195_),
    .B2(_230_),
    .C1(_131_),
    .C2(_231_),
    .ZN(_161_)
  );
  AOI21_X1 _406_ (
    .A(_157_),
    .B1(_160_),
    .B2(_161_),
    .ZN(_120_)
  );
  XNOR2_X1 _407_ (
    .A(_204_),
    .B(_215_),
    .ZN(_162_)
  );
  AOI22_X1 _408_ (
    .A1(_229_),
    .A2(_195_),
    .B1(_131_),
    .B2(_230_),
    .ZN(_163_)
  );
  OAI21_X1 _409_ (
    .A(_163_),
    .B1(_162_),
    .B2(_224_),
    .ZN(_164_)
  );
  MUX2_X1 _410_ (
    .A(_248_),
    .B(_164_),
    .S(_258_),
    .Z(_121_)
  );
  NOR2_X1 _411_ (
    .A1(_205_),
    .A2(_206_),
    .ZN(_165_)
  );
  XNOR2_X1 _412_ (
    .A(_213_),
    .B(_165_),
    .ZN(_166_)
  );
  AOI22_X1 _413_ (
    .A1(_228_),
    .A2(_195_),
    .B1(_131_),
    .B2(_229_),
    .ZN(_167_)
  );
  OAI21_X1 _414_ (
    .A(_167_),
    .B1(_166_),
    .B2(_224_),
    .ZN(_168_)
  );
  MUX2_X1 _415_ (
    .A(_247_),
    .B(_168_),
    .S(_258_),
    .Z(_122_)
  );
  XNOR2_X1 _416_ (
    .A(_256_),
    .B(_130_),
    .ZN(_169_)
  );
  NOR2_X1 _417_ (
    .A1(_257_),
    .A2(_169_),
    .ZN(_123_)
  );
  XNOR2_X1 _418_ (
    .A(_129_),
    .B(_258_),
    .ZN(_170_)
  );
  NOR3_X1 _419_ (
    .A1(_257_),
    .A2(_130_),
    .A3(_170_),
    .ZN(_124_)
  );
  XOR2_X1 _420_ (
    .A(_208_),
    .B(_211_),
    .Z(_171_)
  );
  AOI22_X1 _421_ (
    .A1(_227_),
    .A2(_195_),
    .B1(_131_),
    .B2(_228_),
    .ZN(_172_)
  );
  OAI21_X1 _422_ (
    .A(_172_),
    .B1(_171_),
    .B2(_224_),
    .ZN(_173_)
  );
  MUX2_X1 _423_ (
    .A(_246_),
    .B(_173_),
    .S(_258_),
    .Z(_125_)
  );
  NAND3_X1 _424_ (
    .A1(_226_),
    .A2(_227_),
    .A3(_228_),
    .ZN(_174_)
  );
  AOI221_X1 _425_ (
    .A(_224_),
    .B1(_174_),
    .B2(_211_),
    .C1(_209_),
    .C2(_190_),
    .ZN(_175_)
  );
  AOI221_X1 _426_ (
    .A(_175_),
    .B1(_131_),
    .B2(_227_),
    .C1(_226_),
    .C2(_195_),
    .ZN(_176_)
  );
  NAND2_X1 _427_ (
    .A1(_245_),
    .A2(_192_),
    .ZN(_177_)
  );
  OAI21_X1 _428_ (
    .A(_177_),
    .B1(_176_),
    .B2(_192_),
    .ZN(_126_)
  );
  NAND3_X1 _429_ (
    .A1(_187_),
    .A2(_226_),
    .A3(_227_),
    .ZN(_178_)
  );
  NAND2_X1 _430_ (
    .A1(_226_),
    .A2(_223_),
    .ZN(_179_)
  );
  NAND2_X1 _431_ (
    .A1(_227_),
    .A2(_223_),
    .ZN(_180_)
  );
  OAI21_X1 _432_ (
    .A(_180_),
    .B1(_179_),
    .B2(_225_),
    .ZN(_181_)
  );
  AOI222_X1 _433_ (
    .A1(_225_),
    .A2(_195_),
    .B1(_178_),
    .B2(_181_),
    .C1(_131_),
    .C2(_226_),
    .ZN(_182_)
  );
  NAND2_X1 _434_ (
    .A1(_255_),
    .A2(_192_),
    .ZN(_183_)
  );
  OAI21_X1 _435_ (
    .A(_183_),
    .B1(_182_),
    .B2(_192_),
    .ZN(_127_)
  );
  AOI211_X1 _436_ (
    .A(_187_),
    .B(_195_),
    .C1(_223_),
    .C2(_226_),
    .ZN(_184_)
  );
  OAI21_X1 _437_ (
    .A(_258_),
    .B1(_179_),
    .B2(_225_),
    .ZN(_185_)
  );
  OAI22_X1 _438_ (
    .A1(_254_),
    .A2(_258_),
    .B1(_184_),
    .B2(_185_),
    .ZN(_186_)
  );
  INV_X1 _439_ (
    .A(_186_),
    .ZN(_128_)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _440_ (
    .CK(clk),
    .D(_321_),
    .Q(res_pipe[8]),
    .QN(_288_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _441_ (
    .CK(clk),
    .D(_320_),
    .Q(res_pipe[9]),
    .QN(_261_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _442_ (
    .CK(clk),
    .D(_319_),
    .Q(res_pipe[10]),
    .QN(_287_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _443_ (
    .CK(clk),
    .D(_318_),
    .Q(res_pipe[11]),
    .QN(_263_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _444_ (
    .CK(clk),
    .D(_315_),
    .Q(res_pipe[12]),
    .QN(_266_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _445_ (
    .CK(clk),
    .D(_314_),
    .Q(res_pipe[13]),
    .QN(_267_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _446_ (
    .CK(clk),
    .D(_313_),
    .Q(res_pipe[14]),
    .QN(_268_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _447_ (
    .CK(clk),
    .D(_312_),
    .Q(res_pipe[15]),
    .QN(_269_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _448_ (
    .CK(clk),
    .D(_311_),
    .Q(res_pipe[16]),
    .QN(_270_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _449_ (
    .CK(clk),
    .D(_310_),
    .Q(res_pipe[17]),
    .QN(_271_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _450_ (
    .CK(clk),
    .D(_300_),
    .Q(res_pipe[18]),
    .QN(_281_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _451_ (
    .CK(clk),
    .D(_307_),
    .Q(pixel_out[0]),
    .QN(_274_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _452_ (
    .CK(clk),
    .D(_306_),
    .Q(pixel_out[1]),
    .QN(_275_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _453_ (
    .CK(clk),
    .D(_305_),
    .Q(pixel_out[2]),
    .QN(_276_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _454_ (
    .CK(clk),
    .D(_304_),
    .Q(pixel_out[3]),
    .QN(_277_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _455_ (
    .CK(clk),
    .D(_303_),
    .Q(pixel_out[4]),
    .QN(_278_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _456_ (
    .CK(clk),
    .D(_302_),
    .Q(pixel_out[5]),
    .QN(_279_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _457_ (
    .CK(clk),
    .D(_299_),
    .Q(pixel_out[6]),
    .QN(_282_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _458_ (
    .CK(clk),
    .D(_309_),
    .Q(pixel_out[7]),
    .QN(_272_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _459_ (
    .CK(clk),
    .D(_308_),
    .Q(pixel_out[8]),
    .QN(_273_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _460_ (
    .CK(clk),
    .D(_301_),
    .Q(pixel_out[9]),
    .QN(_283_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:21.5-38.8" *)
  DFFR_X1 _461_ (
    .CK(clk),
    .D(_316_),
    .Q(row),
    .QN(_265_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:21.5-38.8" *)
  DFFR_X1 _462_ (
    .CK(clk),
    .D(_317_),
    .Q(col),
    .QN(_286_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _463_ (
    .CK(clk),
    .D(valid_pipe),
    .Q(valid_out),
    .QN(_284_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _464_ (
    .CK(clk),
    .D(v_pipe),
    .Q(v_sync_out),
    .QN(_260_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _465_ (
    .CK(clk),
    .D(h_pipe),
    .Q(h_sync_out),
    .QN(_280_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _466_ (
    .CK(clk),
    .D(valid_in),
    .Q(valid_pipe),
    .QN(_262_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _467_ (
    .CK(clk),
    .D(h_sync),
    .Q(h_pipe),
    .QN(_264_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _468_ (
    .CK(clk),
    .D(v_sync),
    .Q(v_pipe),
    .QN(_285_),
    .RN(resetn)
  );
  LOGIC0_X1 _469_ (
    .Z(_289_)
  );
  LOGIC0_X1 _470_ (
    .Z(_290_)
  );
  LOGIC0_X1 _471_ (
    .Z(_291_)
  );
  LOGIC0_X1 _472_ (
    .Z(_292_)
  );
  LOGIC0_X1 _473_ (
    .Z(_293_)
  );
  LOGIC0_X1 _474_ (
    .Z(_294_)
  );
  LOGIC0_X1 _475_ (
    .Z(_295_)
  );
  LOGIC0_X1 _476_ (
    .Z(_296_)
  );
  LOGIC0_X1 _477_ (
    .Z(_297_)
  );
  LOGIC0_X1 _478_ (
    .Z(_298_)
  );
  assign { res_pipe[21:19], res_pipe[6:0] } = { _298_, _297_, _296_, _295_, _294_, _293_, _292_, _291_, _290_, _289_ };
  assign _225_ = pixel_in[0];
  assign _256_ = row;
  assign _129_ = col;
  assign _226_ = pixel_in[1];
  assign _227_ = pixel_in[2];
  assign _233_ = pixel_in[8];
  assign _234_ = pixel_in[9];
  assign _232_ = pixel_in[7];
  assign _231_ = pixel_in[6];
  assign _230_ = pixel_in[5];
  assign _228_ = pixel_in[3];
  assign _229_ = pixel_in[4];
  assign _253_ = res_pipe[18];
  assign _251_ = res_pipe[16];
  assign _250_ = res_pipe[15];
  assign _249_ = res_pipe[14];
  assign _248_ = res_pipe[13];
  assign _247_ = res_pipe[12];
  assign _246_ = res_pipe[11];
  assign _245_ = res_pipe[10];
  assign _255_ = res_pipe[9];
  assign _254_ = res_pipe[8];
  assign _257_ = v_sync;
  assign _130_ = h_sync;
  assign _258_ = valid_in;
  assign _252_ = res_pipe[17];
  assign _241_ = pixel_out[6];
  assign _259_ = valid_pipe;
  assign _299_ = _106_;
  assign _300_ = _107_;
  assign _244_ = pixel_out[9];
  assign _301_ = _108_;
  assign _240_ = pixel_out[5];
  assign _302_ = _109_;
  assign _239_ = pixel_out[4];
  assign _303_ = _110_;
  assign _238_ = pixel_out[3];
  assign _304_ = _111_;
  assign _237_ = pixel_out[2];
  assign _305_ = _112_;
  assign _236_ = pixel_out[1];
  assign _306_ = _113_;
  assign _235_ = pixel_out[0];
  assign _307_ = _114_;
  assign _243_ = pixel_out[8];
  assign _308_ = _115_;
  assign _242_ = pixel_out[7];
  assign _309_ = _116_;
  assign _310_ = _117_;
  assign _311_ = _118_;
  assign _312_ = _119_;
  assign _313_ = _120_;
  assign _314_ = _121_;
  assign _315_ = _122_;
  assign _316_ = _123_;
  assign _317_ = _124_;
  assign _318_ = _125_;
  assign _319_ = _126_;
  assign _320_ = _127_;
  assign _321_ = _128_;
endmodule
