/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "src/WBG.v:1.1-83.10" *)
module WBG(clk, resetn, valid_in, v_sync, h_sync, pixel_in, valid_out, v_sync_out, h_sync_out, pixel_out);
  (* src = "src/WBG.v:11.11-11.14" *)
  input clk;
  wire clk;
  (* src = "src/WBG.v:11.16-11.22" *)
  input resetn;
  wire resetn;
  (* src = "src/WBG.v:12.11-12.19" *)
  input valid_in;
  wire valid_in;
  (* src = "src/WBG.v:12.21-12.27" *)
  input v_sync;
  wire v_sync;
  (* src = "src/WBG.v:12.29-12.35" *)
  input h_sync;
  wire h_sync;
  (* src = "src/WBG.v:13.24-13.32" *)
  input [9:0] pixel_in;
  wire [9:0] pixel_in;
  (* src = "src/WBG.v:14.16-14.25" *)
  output valid_out;
  wire valid_out;
  (* src = "src/WBG.v:14.27-14.37" *)
  output v_sync_out;
  wire v_sync_out;
  (* src = "src/WBG.v:14.39-14.49" *)
  output h_sync_out;
  wire h_sync_out;
  (* src = "src/WBG.v:15.29-15.38" *)
  output [9:0] pixel_out;
  wire [9:0] pixel_out;
  (* src = "src/WBG.v:21.5-38.8" *)
  wire _000_;
  (* src = "src/WBG.v:21.5-38.8" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  (* src = "src/WBG.v:20.14-20.17" *)
  wire _025_;
  (* src = "src/WBG.v:12.29-12.35" *)
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _121_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _122_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _123_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _124_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _125_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _126_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _127_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _128_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _129_;
  (* src = "src/WBG.v:13.24-13.32" *)
  wire _130_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _131_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _132_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _133_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _134_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _135_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _136_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _137_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _138_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _139_;
  (* src = "src/WBG.v:15.29-15.38" *)
  wire _140_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _141_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _142_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _143_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _144_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _145_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _146_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _147_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _148_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _149_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _150_;
  (* src = "src/WBG.v:41.40-41.48" *)
  wire _151_;
  (* src = "src/WBG.v:20.9-20.12" *)
  wire _152_;
  (* src = "src/WBG.v:12.21-12.27" *)
  wire _153_;
  (* src = "src/WBG.v:12.11-12.19" *)
  wire _154_;
  (* src = "src/WBG.v:40.20-40.30" *)
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  (* force_downto = 32'd1 *)
  (* src = "src/WBG.v:67.59-67.59|src/WBG.v:64.17-69.24|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" *)
  (* unused_bits = "0" *)
  wire [11:0] _322_;
  (* src = "src/WBG.v:20.14-20.17" *)
  wire col;
  (* src = "src/WBG.v:40.32-40.38" *)
  wire [0:0] h_pipe;
  (* src = "src/WBG.v:41.40-41.48" *)
  (* unused_bits = "7" *)
  wire [21:0] res_pipe;
  (* src = "src/WBG.v:20.9-20.12" *)
  wire row;
  (* src = "src/WBG.v:40.40-40.46" *)
  wire [0:0] v_pipe;
  (* src = "src/WBG.v:40.20-40.30" *)
  wire [0:0] valid_pipe;
  INV_X1 _323_ (
    .A(_121_),
    .ZN(_083_)
  );
  INV_X1 _324_ (
    .A(_129_),
    .ZN(_084_)
  );
  INV_X1 _325_ (
    .A(_128_),
    .ZN(_085_)
  );
  INV_X1 _326_ (
    .A(_124_),
    .ZN(_086_)
  );
  INV_X1 _327_ (
    .A(_149_),
    .ZN(_087_)
  );
  INV_X1 _328_ (
    .A(_154_),
    .ZN(_088_)
  );
  NAND2_X1 _329_ (
    .A1(_087_),
    .A2(_155_),
    .ZN(_089_)
  );
  OAI22_X1 _330_ (
    .A1(_137_),
    .A2(_155_),
    .B1(_089_),
    .B2(_145_),
    .ZN(_090_)
  );
  INV_X1 _331_ (
    .A(_090_),
    .ZN(_020_)
  );
  AND2_X1 _332_ (
    .A1(_152_),
    .A2(_025_),
    .ZN(_091_)
  );
  NOR2_X1 _333_ (
    .A1(_129_),
    .A2(_130_),
    .ZN(_092_)
  );
  NAND2_X1 _334_ (
    .A1(_129_),
    .A2(_128_),
    .ZN(_093_)
  );
  XNOR2_X1 _335_ (
    .A(_129_),
    .B(_128_),
    .ZN(_094_)
  );
  AND2_X1 _336_ (
    .A1(_128_),
    .A2(_127_),
    .ZN(_095_)
  );
  NOR2_X1 _337_ (
    .A1(_128_),
    .A2(_127_),
    .ZN(_096_)
  );
  AND2_X1 _338_ (
    .A1(_127_),
    .A2(_126_),
    .ZN(_097_)
  );
  NAND2_X1 _339_ (
    .A1(_127_),
    .A2(_126_),
    .ZN(_098_)
  );
  OR2_X1 _340_ (
    .A1(_127_),
    .A2(_126_),
    .ZN(_099_)
  );
  NAND2_X1 _341_ (
    .A1(_098_),
    .A2(_099_),
    .ZN(_100_)
  );
  AND2_X1 _342_ (
    .A1(_126_),
    .A2(_125_),
    .ZN(_101_)
  );
  NOR2_X1 _343_ (
    .A1(_126_),
    .A2(_125_),
    .ZN(_102_)
  );
  NAND2_X1 _344_ (
    .A1(_124_),
    .A2(_125_),
    .ZN(_103_)
  );
  XNOR2_X1 _345_ (
    .A(_124_),
    .B(_125_),
    .ZN(_104_)
  );
  AOI21_X1 _346_ (
    .A(_123_),
    .B1(_122_),
    .B2(_121_),
    .ZN(_105_)
  );
  AOI21_X1 _347_ (
    .A(_124_),
    .B1(_123_),
    .B2(_122_),
    .ZN(_106_)
  );
  NOR2_X1 _348_ (
    .A1(_105_),
    .A2(_106_),
    .ZN(_107_)
  );
  OR3_X1 _349_ (
    .A1(_104_),
    .A2(_105_),
    .A3(_106_),
    .ZN(_108_)
  );
  NAND2_X1 _350_ (
    .A1(_103_),
    .A2(_108_),
    .ZN(_109_)
  );
  AOI21_X1 _351_ (
    .A(_102_),
    .B1(_103_),
    .B2(_108_),
    .ZN(_110_)
  );
  NOR2_X1 _352_ (
    .A1(_101_),
    .A2(_110_),
    .ZN(_111_)
  );
  OR2_X1 _353_ (
    .A1(_101_),
    .A2(_110_),
    .ZN(_112_)
  );
  OAI21_X1 _354_ (
    .A(_098_),
    .B1(_100_),
    .B2(_111_),
    .ZN(_113_)
  );
  AOI211_X1 _355_ (
    .A(_095_),
    .B(_097_),
    .C1(_099_),
    .C2(_112_),
    .ZN(_114_)
  );
  OR3_X1 _356_ (
    .A1(_094_),
    .A2(_096_),
    .A3(_114_),
    .ZN(_115_)
  );
  OAI21_X1 _357_ (
    .A(_129_),
    .B1(_130_),
    .B2(_128_),
    .ZN(_116_)
  );
  OAI21_X1 _358_ (
    .A(_116_),
    .B1(_115_),
    .B2(_092_),
    .ZN(_117_)
  );
  NOR2_X1 _359_ (
    .A1(_091_),
    .A2(_117_),
    .ZN(_118_)
  );
  NOR2_X1 _360_ (
    .A1(_152_),
    .A2(_025_),
    .ZN(_119_)
  );
  OR2_X1 _361_ (
    .A1(_152_),
    .A2(_025_),
    .ZN(_120_)
  );
  NOR2_X1 _362_ (
    .A1(_091_),
    .A2(_119_),
    .ZN(_027_)
  );
  OAI211_X1 _363_ (
    .A(_130_),
    .B(_154_),
    .C1(_091_),
    .C2(_119_),
    .ZN(_028_)
  );
  OAI22_X1 _364_ (
    .A1(_087_),
    .A2(_154_),
    .B1(_118_),
    .B2(_028_),
    .ZN(_021_)
  );
  OAI22_X1 _365_ (
    .A1(_155_),
    .A2(_140_),
    .B1(_089_),
    .B2(_148_),
    .ZN(_029_)
  );
  INV_X1 _366_ (
    .A(_029_),
    .ZN(_022_)
  );
  OAI22_X1 _367_ (
    .A1(_155_),
    .A2(_136_),
    .B1(_089_),
    .B2(_144_),
    .ZN(_030_)
  );
  INV_X1 _368_ (
    .A(_030_),
    .ZN(_023_)
  );
  OAI22_X1 _369_ (
    .A1(_155_),
    .A2(_135_),
    .B1(_089_),
    .B2(_143_),
    .ZN(_031_)
  );
  INV_X1 _370_ (
    .A(_031_),
    .ZN(_024_)
  );
  OAI22_X1 _371_ (
    .A1(_155_),
    .A2(_134_),
    .B1(_089_),
    .B2(_142_),
    .ZN(_032_)
  );
  INV_X1 _372_ (
    .A(_032_),
    .ZN(_002_)
  );
  OAI22_X1 _373_ (
    .A1(_155_),
    .A2(_133_),
    .B1(_089_),
    .B2(_141_),
    .ZN(_033_)
  );
  INV_X1 _374_ (
    .A(_033_),
    .ZN(_003_)
  );
  OAI22_X1 _375_ (
    .A1(_155_),
    .A2(_132_),
    .B1(_089_),
    .B2(_151_),
    .ZN(_034_)
  );
  INV_X1 _376_ (
    .A(_034_),
    .ZN(_004_)
  );
  OAI22_X1 _377_ (
    .A1(_155_),
    .A2(_131_),
    .B1(_089_),
    .B2(_150_),
    .ZN(_035_)
  );
  INV_X1 _378_ (
    .A(_035_),
    .ZN(_005_)
  );
  OAI22_X1 _379_ (
    .A1(_155_),
    .A2(_139_),
    .B1(_089_),
    .B2(_147_),
    .ZN(_036_)
  );
  INV_X1 _380_ (
    .A(_036_),
    .ZN(_006_)
  );
  OAI22_X1 _381_ (
    .A1(_155_),
    .A2(_138_),
    .B1(_089_),
    .B2(_146_),
    .ZN(_037_)
  );
  INV_X1 _382_ (
    .A(_037_),
    .ZN(_007_)
  );
  NOR2_X1 _383_ (
    .A1(_154_),
    .A2(_148_),
    .ZN(_038_)
  );
  AOI211_X1 _384_ (
    .A(_084_),
    .B(_130_),
    .C1(_085_),
    .C2(_115_),
    .ZN(_039_)
  );
  AND3_X1 _385_ (
    .A1(_084_),
    .A2(_130_),
    .A3(_115_),
    .ZN(_040_)
  );
  OAI21_X1 _386_ (
    .A(_119_),
    .B1(_039_),
    .B2(_040_),
    .ZN(_041_)
  );
  AOI221_X1 _387_ (
    .A(_088_),
    .B1(_091_),
    .B2(_129_),
    .C1(_027_),
    .C2(_130_),
    .ZN(_042_)
  );
  AOI21_X1 _388_ (
    .A(_038_),
    .B1(_041_),
    .B2(_042_),
    .ZN(_008_)
  );
  NOR2_X1 _389_ (
    .A1(_147_),
    .A2(_154_),
    .ZN(_043_)
  );
  XOR2_X1 _390_ (
    .A(_129_),
    .B(_130_),
    .Z(_044_)
  );
  AND3_X1 _391_ (
    .A1(_093_),
    .A2(_115_),
    .A3(_044_),
    .ZN(_045_)
  );
  AOI21_X1 _392_ (
    .A(_044_),
    .B1(_115_),
    .B2(_093_),
    .ZN(_046_)
  );
  OAI21_X1 _393_ (
    .A(_119_),
    .B1(_045_),
    .B2(_046_),
    .ZN(_047_)
  );
  AOI221_X1 _394_ (
    .A(_088_),
    .B1(_091_),
    .B2(_128_),
    .C1(_027_),
    .C2(_129_),
    .ZN(_048_)
  );
  AOI21_X1 _395_ (
    .A(_043_),
    .B1(_047_),
    .B2(_048_),
    .ZN(_009_)
  );
  NOR2_X1 _396_ (
    .A1(_146_),
    .A2(_154_),
    .ZN(_049_)
  );
  OAI21_X1 _397_ (
    .A(_094_),
    .B1(_096_),
    .B2(_114_),
    .ZN(_050_)
  );
  NAND3_X1 _398_ (
    .A1(_115_),
    .A2(_119_),
    .A3(_050_),
    .ZN(_051_)
  );
  AOI221_X1 _399_ (
    .A(_088_),
    .B1(_091_),
    .B2(_127_),
    .C1(_027_),
    .C2(_128_),
    .ZN(_052_)
  );
  AOI21_X1 _400_ (
    .A(_049_),
    .B1(_051_),
    .B2(_052_),
    .ZN(_010_)
  );
  NOR2_X1 _401_ (
    .A1(_145_),
    .A2(_154_),
    .ZN(_053_)
  );
  OR2_X1 _402_ (
    .A1(_095_),
    .A2(_096_),
    .ZN(_054_)
  );
  XNOR2_X1 _403_ (
    .A(_113_),
    .B(_054_),
    .ZN(_055_)
  );
  NAND2_X1 _404_ (
    .A1(_119_),
    .A2(_055_),
    .ZN(_056_)
  );
  AOI221_X1 _405_ (
    .A(_088_),
    .B1(_091_),
    .B2(_126_),
    .C1(_027_),
    .C2(_127_),
    .ZN(_057_)
  );
  AOI21_X1 _406_ (
    .A(_053_),
    .B1(_056_),
    .B2(_057_),
    .ZN(_011_)
  );
  XNOR2_X1 _407_ (
    .A(_100_),
    .B(_111_),
    .ZN(_058_)
  );
  AOI22_X1 _408_ (
    .A1(_125_),
    .A2(_091_),
    .B1(_027_),
    .B2(_126_),
    .ZN(_059_)
  );
  OAI21_X1 _409_ (
    .A(_059_),
    .B1(_058_),
    .B2(_120_),
    .ZN(_060_)
  );
  MUX2_X1 _410_ (
    .A(_144_),
    .B(_060_),
    .S(_154_),
    .Z(_012_)
  );
  NOR2_X1 _411_ (
    .A1(_101_),
    .A2(_102_),
    .ZN(_061_)
  );
  XNOR2_X1 _412_ (
    .A(_109_),
    .B(_061_),
    .ZN(_062_)
  );
  AOI22_X1 _413_ (
    .A1(_124_),
    .A2(_091_),
    .B1(_027_),
    .B2(_125_),
    .ZN(_063_)
  );
  OAI21_X1 _414_ (
    .A(_063_),
    .B1(_062_),
    .B2(_120_),
    .ZN(_064_)
  );
  MUX2_X1 _415_ (
    .A(_143_),
    .B(_064_),
    .S(_154_),
    .Z(_013_)
  );
  XNOR2_X1 _416_ (
    .A(_152_),
    .B(_026_),
    .ZN(_065_)
  );
  NOR2_X1 _417_ (
    .A1(_153_),
    .A2(_065_),
    .ZN(_014_)
  );
  XNOR2_X1 _418_ (
    .A(_025_),
    .B(_154_),
    .ZN(_066_)
  );
  NOR3_X1 _419_ (
    .A1(_153_),
    .A2(_026_),
    .A3(_066_),
    .ZN(_015_)
  );
  XOR2_X1 _420_ (
    .A(_104_),
    .B(_107_),
    .Z(_067_)
  );
  AOI22_X1 _421_ (
    .A1(_123_),
    .A2(_091_),
    .B1(_027_),
    .B2(_124_),
    .ZN(_068_)
  );
  OAI21_X1 _422_ (
    .A(_068_),
    .B1(_067_),
    .B2(_120_),
    .ZN(_069_)
  );
  MUX2_X1 _423_ (
    .A(_142_),
    .B(_069_),
    .S(_154_),
    .Z(_016_)
  );
  NAND3_X1 _424_ (
    .A1(_122_),
    .A2(_123_),
    .A3(_124_),
    .ZN(_070_)
  );
  AOI221_X1 _425_ (
    .A(_120_),
    .B1(_070_),
    .B2(_107_),
    .C1(_105_),
    .C2(_086_),
    .ZN(_071_)
  );
  AOI221_X1 _426_ (
    .A(_071_),
    .B1(_027_),
    .B2(_123_),
    .C1(_122_),
    .C2(_091_),
    .ZN(_072_)
  );
  NAND2_X1 _427_ (
    .A1(_141_),
    .A2(_088_),
    .ZN(_073_)
  );
  OAI21_X1 _428_ (
    .A(_073_),
    .B1(_072_),
    .B2(_088_),
    .ZN(_017_)
  );
  NAND3_X1 _429_ (
    .A1(_083_),
    .A2(_122_),
    .A3(_123_),
    .ZN(_074_)
  );
  NAND2_X1 _430_ (
    .A1(_122_),
    .A2(_119_),
    .ZN(_075_)
  );
  NAND2_X1 _431_ (
    .A1(_123_),
    .A2(_119_),
    .ZN(_076_)
  );
  OAI21_X1 _432_ (
    .A(_076_),
    .B1(_075_),
    .B2(_121_),
    .ZN(_077_)
  );
  AOI222_X1 _433_ (
    .A1(_121_),
    .A2(_091_),
    .B1(_074_),
    .B2(_077_),
    .C1(_027_),
    .C2(_122_),
    .ZN(_078_)
  );
  NAND2_X1 _434_ (
    .A1(_151_),
    .A2(_088_),
    .ZN(_079_)
  );
  OAI21_X1 _435_ (
    .A(_079_),
    .B1(_078_),
    .B2(_088_),
    .ZN(_018_)
  );
  AOI211_X1 _436_ (
    .A(_083_),
    .B(_091_),
    .C1(_119_),
    .C2(_122_),
    .ZN(_080_)
  );
  OAI21_X1 _437_ (
    .A(_154_),
    .B1(_075_),
    .B2(_121_),
    .ZN(_081_)
  );
  OAI22_X1 _438_ (
    .A1(_150_),
    .A2(_154_),
    .B1(_080_),
    .B2(_081_),
    .ZN(_082_)
  );
  INV_X1 _439_ (
    .A(_082_),
    .ZN(_019_)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _440_ (
    .CK(clk),
    .D(_316_),
    .Q(res_pipe[8]),
    .QN(_288_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _441_ (
    .CK(clk),
    .D(_315_),
    .Q(res_pipe[9]),
    .QN(_261_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _442_ (
    .CK(clk),
    .D(_314_),
    .Q(res_pipe[10]),
    .QN(_287_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _443_ (
    .CK(clk),
    .D(_313_),
    .Q(res_pipe[11]),
    .QN(_263_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _444_ (
    .CK(clk),
    .D(_310_),
    .Q(res_pipe[12]),
    .QN(_266_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _445_ (
    .CK(clk),
    .D(_309_),
    .Q(res_pipe[13]),
    .QN(_267_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _446_ (
    .CK(clk),
    .D(_308_),
    .Q(res_pipe[14]),
    .QN(_268_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _447_ (
    .CK(clk),
    .D(_307_),
    .Q(res_pipe[15]),
    .QN(_269_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _448_ (
    .CK(clk),
    .D(_306_),
    .Q(res_pipe[16]),
    .QN(_270_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _449_ (
    .CK(clk),
    .D(_305_),
    .Q(res_pipe[17]),
    .QN(_271_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _450_ (
    .CK(clk),
    .D(_318_),
    .Q(res_pipe[18]),
    .QN(_281_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _451_ (
    .CK(clk),
    .D(_302_),
    .Q(pixel_out[0]),
    .QN(_274_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _452_ (
    .CK(clk),
    .D(_301_),
    .Q(pixel_out[1]),
    .QN(_275_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _453_ (
    .CK(clk),
    .D(_300_),
    .Q(pixel_out[2]),
    .QN(_276_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _454_ (
    .CK(clk),
    .D(_299_),
    .Q(pixel_out[3]),
    .QN(_277_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _455_ (
    .CK(clk),
    .D(_321_),
    .Q(pixel_out[4]),
    .QN(_278_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _456_ (
    .CK(clk),
    .D(_320_),
    .Q(pixel_out[5]),
    .QN(_279_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _457_ (
    .CK(clk),
    .D(_317_),
    .Q(pixel_out[6]),
    .QN(_282_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _458_ (
    .CK(clk),
    .D(_304_),
    .Q(pixel_out[7]),
    .QN(_272_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _459_ (
    .CK(clk),
    .D(_303_),
    .Q(pixel_out[8]),
    .QN(_273_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _460_ (
    .CK(clk),
    .D(_319_),
    .Q(pixel_out[9]),
    .QN(_283_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:21.5-38.8" *)
  DFFR_X1 _461_ (
    .CK(clk),
    .D(_311_),
    .Q(row),
    .QN(_265_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:21.5-38.8" *)
  DFFR_X1 _462_ (
    .CK(clk),
    .D(_312_),
    .Q(col),
    .QN(_286_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _463_ (
    .CK(clk),
    .D(valid_pipe),
    .Q(valid_out),
    .QN(_284_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _464_ (
    .CK(clk),
    .D(v_pipe),
    .Q(v_sync_out),
    .QN(_260_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _465_ (
    .CK(clk),
    .D(h_pipe),
    .Q(h_sync_out),
    .QN(_280_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _466_ (
    .CK(clk),
    .D(valid_in),
    .Q(valid_pipe),
    .QN(_262_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _467_ (
    .CK(clk),
    .D(h_sync),
    .Q(h_pipe),
    .QN(_264_),
    .RN(resetn)
  );
  (* src = "src/WBG.v:43.5-81.8" *)
  DFFR_X1 _468_ (
    .CK(clk),
    .D(v_sync),
    .Q(v_pipe),
    .QN(_285_),
    .RN(resetn)
  );
  LOGIC0_X1 _469_ (
    .Z(_289_)
  );
  LOGIC0_X1 _470_ (
    .Z(_290_)
  );
  LOGIC0_X1 _471_ (
    .Z(_291_)
  );
  LOGIC0_X1 _472_ (
    .Z(_292_)
  );
  LOGIC0_X1 _473_ (
    .Z(_293_)
  );
  LOGIC0_X1 _474_ (
    .Z(_294_)
  );
  LOGIC0_X1 _475_ (
    .Z(_295_)
  );
  LOGIC0_X1 _476_ (
    .Z(_296_)
  );
  LOGIC0_X1 _477_ (
    .Z(_297_)
  );
  LOGIC0_X1 _478_ (
    .Z(_298_)
  );
  assign { res_pipe[21:19], res_pipe[6:0] } = { _298_, _297_, _296_, _295_, _294_, _293_, _292_, _291_, _290_, _289_ };
  assign _121_ = pixel_in[0];
  assign _152_ = row;
  assign _025_ = col;
  assign _122_ = pixel_in[1];
  assign _123_ = pixel_in[2];
  assign _129_ = pixel_in[8];
  assign _130_ = pixel_in[9];
  assign _128_ = pixel_in[7];
  assign _127_ = pixel_in[6];
  assign _126_ = pixel_in[5];
  assign _124_ = pixel_in[3];
  assign _125_ = pixel_in[4];
  assign _149_ = res_pipe[18];
  assign _147_ = res_pipe[16];
  assign _146_ = res_pipe[15];
  assign _145_ = res_pipe[14];
  assign _144_ = res_pipe[13];
  assign _143_ = res_pipe[12];
  assign _142_ = res_pipe[11];
  assign _141_ = res_pipe[10];
  assign _151_ = res_pipe[9];
  assign _150_ = res_pipe[8];
  assign _153_ = v_sync;
  assign _026_ = h_sync;
  assign _154_ = valid_in;
  assign _148_ = res_pipe[17];
  assign _137_ = pixel_out[6];
  assign _155_ = valid_pipe;
  assign _317_ = _020_;
  assign _318_ = _021_;
  assign _140_ = pixel_out[9];
  assign _319_ = _022_;
  assign _136_ = pixel_out[5];
  assign _320_ = _023_;
  assign _135_ = pixel_out[4];
  assign _321_ = _024_;
  assign _134_ = pixel_out[3];
  assign _299_ = _002_;
  assign _133_ = pixel_out[2];
  assign _300_ = _003_;
  assign _132_ = pixel_out[1];
  assign _301_ = _004_;
  assign _131_ = pixel_out[0];
  assign _302_ = _005_;
  assign _139_ = pixel_out[8];
  assign _303_ = _006_;
  assign _138_ = pixel_out[7];
  assign _304_ = _007_;
  assign _305_ = _008_;
  assign _306_ = _009_;
  assign _307_ = _010_;
  assign _308_ = _011_;
  assign _309_ = _012_;
  assign _310_ = _013_;
  assign _311_ = _014_;
  assign _312_ = _015_;
  assign _313_ = _016_;
  assign _314_ = _017_;
  assign _315_ = _018_;
  assign _316_ = _019_;
endmodule
